### ISSUE TITLE
Can't resolve libportal-gtk3

### ISSUE THREAD

**Issue by benbrastmckie** [lubomir-brindza/nautilus-typeahead#10]
I'm getting the following error upon running `sudo pacman -S nautilus-typeahead`:
```
warning: cannot resolve "libportal-gtk3", a dependency of "nautilus-typeahead"
```
I'm trying to install `nautilus-typeahead` because Nautilus stopped working after running a system update. Any help would be much appreciated.

**Comment by lubomir-brindza** [comment]
@benbrastmckie sorry, but this looks  Arch-specific. But feel free to update if you've found a way to solve this, maybe it'll help the next unlucky soul.

**Comment by benbrastmckie** [comment]
The issue was to do with a conflict I was having with Zotero, and yes probably Arch specific. Anyhow, I removed Zotero, updated pacman, and reinstalled Zotero. All is working now.
