### ISSUE TITLE
Sobbing for Gnome 42 support

### ISSUE THREAD

**Issue by ttytm** [lubomir-brindza/nautilus-typeahead#11]
Cyring myself silently into sleep about loosing this feature after updating. 
Is there an outlook for sunnier days with v42 support?

**Comment by lubomir-brindza** [comment]
Sure; I'll try to have it up by today or tomorrow.

**Comment by lubomir-brindza** [comment]
Done; PPA package for jaunty is up.

**Comment by ttytm** [comment]
Heroic! 

Love and blessings :heart: :raised_hands:
