### ISSUE TITLE
nautilus-typeahead is out of date on 22.04 jammy jellyfish

### ISSUE THREAD

**Issue by sbrl** [lubomir-brindza/nautilus-typeahead#13]
I've just upgraded to Ubuntu 22.04 Jammy Jellyfish, and the version of nautilus in the default repos is `1:42.1.1-0ubuntu1` vs the `42.0-1ubuntu2ppa1` available in your nautilus-typeahead ppa?

**Comment by lubomir-brindza** [comment]
Hi, the package has been rebuilt and it's now pending publication; should be a couple of hours, tops.
