### ISSUE TITLE
Updated packages on 22.04

### ISSUE THREAD

**Issue by lpinner** [lubomir-brindza/nautilus-typeahead#15]
1:42.2-0ubuntu1 from jammy-updates is installing over 1:42.1.1-0ubuntuppa1 from the ppa

**Comment by lubomir-brindza** [comment]
Sorry it took so long; my local mirror didn't have the updated source at the time (still doesn't in fact), so I got distracted while waiting >_>

Package was submitted for building; should be up within an hour or so.

e: It's up.
