### ISSUE TITLE
No longer working on Ubuntu 20

### ISSUE THREAD

**Issue by ValentinSteiner** [lubomir-brindza/nautilus-typeahead#17]
There seems to be a new Nautilus version in the official repositories which disabled the PPA.

The new version (from 2023-01-03) is `1:3.36.3-0ubuntu1.20.04.2` (https://bugs.launchpad.net/ubuntu/+source/nautilus/1:3.36.3-0ubuntu1.20.04.2).

As an aside, make sure to click "Affects me" on the two Launchpad issues, so that maybe this will return to the main repo at some point in the future.
* https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1767431
* https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1754069

**Comment by lubomir-brindza** [comment]
A new patched release (`3.36.3-0ubuntu1.20.04.2ppa0`) should be available in the PPA within a few hours.
