### ISSUE TITLE
The pop-up window seems to last longer than expected. Ubuntu 22.04

### ISSUE THREAD

**Issue by cyfex** [lubomir-brindza/nautilus-typeahead#18]
Hi, first of all I love the author because this is my favorite deb across all versions of Ubuntu.

I just upgrade my system to Ubuntu 22.04, with gnome-flashback. I notice that if I type ahead a few characters, then alt+tab, the pop-up window will keep hanging there until 3 to 5 secs. If my memory works it is not the case back in Ubuntu 20.04. Is it intended or just a bug?

**Comment by cyfex** [comment]
Is there anyone following this issue?

**Comment by lubomir-brindza** [comment]
Hi @cyfex - no, no one is working on this issue, and chances that it'll get addressed in the future are pretty much nonexistent.

It's relatively harmless, affects an outdated version of nautilus, and isn't present in newer versions (as both nautilus and typeahed restoration patch went through a significant rewrite in the meantime).

Sorry for not closing this sooner.
