### ISSUE TITLE
Update to 1:3.26.4

### ISSUE THREAD

**Issue by gerhardj** [lubomir-brindza/nautilus-typeahead#2]
Hi, it seems this PPA needs to be updated to the new version of nautilus, since currently my PPA won't install anything.

**Comment by lubomir-brindza** [comment]
Hi, sorry about the response time, the PPA has been updated a few days ago (2018/10/04, IIRC). There were no changes to the patch necessary, it still applied cleanly.

**Comment by brunetton** [comment]
Thanks you so much for this wonderfull fork !!! This literally save my life, everyday !
