### ISSUE TITLE
mx linux installation

### ISSUE THREAD

**Issue by peterweissbier** [lubomir-brindza/nautilus-typeahead#20]
hi, can you guide me on how to get this working on mx linux?

**Comment by lubomir-brindza** [comment]
Sorry, can't; I don't have personal experience with MX Linux (didn't know it existed until today, in fact). I assume you tried going through the steps detailed in https://mxlinux.org/wiki/system/add-ppa-repository/ already?

Honestly, I'm not sure this package'll work in anything besides Ubuntu, whether it's Debian-based or not.

**Comment by peterweissbier** [comment]
yeah, adding the repository or patching both failed. thanks
