### ISSUE TITLE
Not working anymore on 18.04?

### ISSUE THREAD

**Issue by MatthieuStigler** [lubomir-brindza/nautilus-typeahead#5]
Hi

Thanks a lot for this extension, to be honest I maybe would not be on Ubuntu anymore for it!

I used it for a while on 18.04, although recently it stopped working, i.e. the other search style came back. Any idea why? Could this be to an update in nautilus? I have version `GNOME nautilus 3.26.4` now.

Thanks!

**Comment by internetcoffeephone** [comment]
Can confirm this report: I also just encountered this issue in version `GNOME nautilus 3.26.4` with `Ubuntu 18.04` right after updating my system.

**Comment by lubomir-brindza** [comment]
Hi, thanks for letting me know. I've pushed an updated package to PPA, it's currently being built. It should be available to get via apt within an hour or two.

**Comment by lubomir-brindza** [comment]
Alright, no such luck. The build's failing even though the patch applies; will need to have a good look at why. I'll try to have it out as soon as possible, but it probably won't be today, sorry.

**Comment by lumenwrites** [comment]
@lubomir-brindza Hi! Just found this thread because I've encountered the same issue.

While I'm here I want to say - thank you SO much for working on this, it is incredibly valuable, nautilus is not usable without your project!

**Comment by lubomir-brindza** [comment]
Sorry about the delay; the issue seems to be fixed and Launchpad built the 18.04 package w/o further issues. Let me know if there are any issues with it (I don't actually have an 18.04 desktop ATM to test >_>)

**Comment by Thijsvanede** [comment]
Thank you so much! It works like a charm again :)

**Comment by MatthieuStigler** [comment]
Confirmed, it worked!

Thanks!!
