### ISSUE TITLE
Patch breaks gnome-sushi

### ISSUE THREAD

**Issue by wyphan** [lubomir-brindza/nautilus-typeahead#6]
Hi, thanks for bringing back this feature! I really wish gnome-sushi file previewer still works with this patched version though... especially since it works by pressing the spacebar.

Edit: this might have been fixed on upstream? [comment](https://aur.archlinux.org/pkgbase/nautilus-typeahead/#comment-709663)

**Comment by Magneticdud** [comment]
I guess latest update (2021-06-04) fixed the problem, gnome-sushi works fine for me. If you type something else, then press space, it will add a space in what you typed, but imho that would be expected by design
