### ISSUE TITLE
Consider filing an upstream pull request

### ISSUE THREAD

**Issue by chrisjbillington** [lubomir-brindza/nautilus-typeahead#7]
The latest upstream issue asking for this feature is here:

https://gitlab.gnome.org/GNOME/nautilus/-/issues/1157

In the past "show us the code in a form we can review" has been a cited reason for not considering patches elsewhere for typeahead behaviour. Whilst I think this is likely to just be a polite way of telling people to go away, since the code exists already perhaps you might consider making a merge request on the nautilus gitlab project.

**Comment by lubomir-brindza** [comment]
Hi, thanks for getting in touch, but I'll have to respectfully decline.

Firstly, I didn't write any of this, it's just a fork of an Arch AUR repository: https://aur.archlinux.org/packages/nautilus-typeahead/

The reason for this repository's existence is mostly that people that do decide to use the PPA package can see what goes into it (and to request rebuilding the package should I miss a new release). The current master version of the patch does not have any differences from the upstream (Arch) version. This was not always the case, but it is now, so: moot point.

Also, Gnome team have shown remarkable consistency in shooting down the idea of reintroducing this feature so so many times, I have a hard time believing it would go differently this time.
