### ISSUE TITLE
Left and Right arrow navigation does not work when typing-ahead (in thumbnail view)

### ISSUE THREAD

**Issue by nlflint** [lubomir-brindza/nautilus-typeahead#8]
Sometimes the file/folder I'm targeting is one or two places to the right, and I would like to be able to press the right arrow key and enter to select it, while in thumbnail view.

Repro:

1. Given a folder with 2 subfolders named: "New Folder" and "New Folder 1"
2. Open Nautilus to the folder in step 1
3. Put Nautilus into **thumb-nail** view mode
4. Type "new"
5. "New Folder" is selected
6. Press right arrow to select "New Folder 1"

Expected: New Folder 1 is selected
Actual: "New Folder" is still selected; the selection doesn't change

Curiously, UP and DOWN arrow keys will change the selection left/right. This is unexpected.

**Comment by lubomir-brindza** [comment]
The arrow situation is in my opinion (and note that I didn't make the design decision, I'm just a fellow user) a pretty decent compromise, considering the UI of the current typeahead implementation (i.e.: via text entry widget). Capturing left/right arrow keystrokes for purposes of changing file/folder selection would necessarily take focus from the text cursor.

Whether that text box is really necessary is a different matter entirely, but that's for upstream developer(s) to decide.

This repository's purpose isn't to add or change any functionality WRT to upstream (Arch) patch, only to track changes that are sometimes necessary for it to cleanly apply to nautilus source in Ubuntu's repositories.

**Comment by mdmower** [comment]
> Whether that text box is really necessary is a different matter entirely

... this makes me smile because I dislike that text box and based on your comment, I think you do, too 🙂.

**Comment by lubomir-brindza** [comment]
The new version (43.0, Ubuntu 22.10) seems to behave just like described, so I'll close this issue.
