### ISSUE TITLE
Please add README

### ISSUE THREAD

**Issue by Mr-Goldberg** [lubomir-brindza/nautilus-typeahead#9]
Hi!
Thank you for restoring this feature.
Could you please add a very short instruction on how to use this patch? I've spent some time figuring it out. The guides over the internet leading to this repo are not clear or not working completely.

What's worked for me (in terminal):
sudo add-apt-repository ppa:lubomir-brindza/nautilus-typeahead
sudo apt dist-upgrade
nautilus -q && nautilus &

**Comment by lubomir-brindza** [comment]
You're absolutely right; I'll try to put something together.

**Comment by NatoBoram** [comment]
Speaking of `README.md`, I had some difficulty installing this package from the PPA, it didn't immediately work. Here's what I had to do : 

```bash
sudo add-apt-repository ppa:lubomir-brindza/nautilus-typeahead
sudo apt upgrade
killall nautilus
```

I think it would be awesome to have that in the `README.md`.
